### ISSUE TITLE
madrona_escape_room module causes Python to hang

### ISSUE THREAD

**Issue by Andrew-Luo1** [shacklettbp/madrona_3d_example#8]
Hi, thanks for this well-written demo. I followed the instructions in the readme for Ubuntu and am getting reasonable training results. However, I'm having a weird bug.

**Q1: Bug?**

Running the below file as `python test.py`, the program does not exit after calling the two imports.
``` test.py
import torch
import madrona_escape_room
```
However, it exits as usual when I have just the second line or flip the order of the imports.

**Q2: Developer's setup**

In the case this bug turns out to be tough to reproduce/fix, could you share the software versions you used in development? It might just be easier to switch to your setup to avoid any future strange bugs.

**Q3: Benchmarking**

When I run:

`python scripts/train.py --num-worlds 2048 --num-updates 1000 --profile-report --fp16 --gpu-sim --ckpt-dir build/checkpoints/`

on an Nvidia 4060Ti 8GB, I get around 260k FPS. Would you be able to assess whether this seems reasonable?

**Setup**

OS: Ubuntu 22.04.5 LTS
Pytorch: 2.4.1
Cuda: CUDA Toolkit 12.4.0 (March 2024)
GPU: NVIDIA GeForce RTX 4060 Ti

**Comment by shacklettbp** [comment]
Thanks for the report! This project was a bit out of date with the latest version of Madrona. I've just updated it - please let me know if you can still reproduce the issue (I cannot after the update).

You'll need to do `git submodule update --init --recursive`

**Comment by shacklettbp** [comment]
Closing this for now, feel free to reopen if the issue still exists.

**Comment by Andrew-Luo1** [comment]
Issue is resolved, thanks!
