### ISSUE TITLE
NVRTC_ERROR_COMPILATION

### ISSUE THREAD

**Issue by ShawnshanksGui** [shacklettbp/madrona_3d_example#9]
Hi, I tried to run the 'main' branch of this repo, but cannot run successfully:
```
git clone --recursive git@github.com:shacklettbp/madrona_escape_room.git
cd ./madrona_escape_room/
mkdir build
cmake ..
make -j 60
cd ..
pip install -e .
python scripts/train.py --num-worlds 8192 --num-updates 5000 --profile-report --fp16 --gpu-sim --ckpt-dir build/checkpoints/
```

NVRTC_ERROR_COMPILATION happened as following:
 
![image](https://github.com/user-attachments/assets/68a9c00c-de6e-4fb4-974a-9be65143b958)
![image](https://github.com/user-attachments/assets/7204fb51-cd97-4bde-9af5-5ccc873451a8)

Any guidance on how to resolve this would be appreciated.

**Comment by shacklettbp** [comment]
It's a CUDA bug: https://github.com/shacklettbp/madrona/issues/39

You need to downgrade to CUDA 12.5. We've been told by NVIDIA that they've fixed this issue in CUDA 12.8, coming in January.

**Comment by ShawnshanksGui** [comment]
I switch to CUDA 12.5, but still failed:

CUDA 12.5, NVIDIA driver 560.35.05. 
The Torch version is as follows (): 
![image](https://github.com/user-attachments/assets/14dd7560-ac67-434d-aed7-26c083373761)

![image](https://github.com/user-attachments/assets/61862a5c-c729-4d87-a283-91ba23880525)

The error info is as follows:
![image](https://github.com/user-attachments/assets/94c2fdd8-0545-44e9-b0a1-413caa7deba7)

**Comment by shacklettbp** [comment]
Those errors indicate Madrona is pulling in CUDA 12.6 or newer. You probably have CUDA 12.6 installed somewhere on your machine and CMake is building against it. Or some other library is pulling it in at runtime.

**Comment by ShawnshanksGui** [comment]
thx, I fixed it.
but a small new problem occurred:
![image](https://github.com/user-attachments/assets/f3a1ae52-f281-413a-a84a-1bd257d9c93b)

**Comment by shacklettbp** [comment]
Weird, I don't think there's enough information in that screenshot for me to help though. Where in Madrona code is that error happening?

**Comment by ShawnshanksGui** [comment]
Sorry for the lack of context. 
There are no errors occurring during the compilation phase.
The error happened when I run the command "python scripts/train.py --num-worlds 1 --num-updates 10 --ckpt-dir build/ckpts (--gpu-sim)"
![image](https://github.com/user-attachments/assets/3867ea04-be8e-41f3-b033-4195e4f4dacf)

![image](https://github.com/user-attachments/assets/fa66d6ef-a356-482a-8070-dcd047ff7fb7)

**Comment by ShawnshanksGui** [comment]
More detail context info: CUDA 12.5, NVIDIA driver 560.35.05,  python 3.12.8,  cmake 3.27.6
torch: 
![image](https://github.com/user-attachments/assets/d04300c9-98b3-4c2e-9969-c1fbbb9e10ec)

**Comment by shacklettbp** [comment]
I can't help without a full backtrace that shows where in the training script this crash is happening. You could try launching the train script under pdb (python debugger) if you're not getting a full backtrace printed to the console for some reason.

**Comment by ShawnshanksGui** [comment]
It seems a warning, not an error.
![image](https://github.com/user-attachments/assets/6af2d8e4-1428-448d-9542-38ef1a8b7b58)

**Comment by shacklettbp** [comment]
I see, I'm not sure what's causing this, sorry. It looks like it only happens at the end of the training run because something on the python side isn't cleaning up a temporary directory when the process exits. If you can track down the issue I'd be happy to accept a PR to fix it, but I'm not actively using the training code in this repo anymore, so I don't have time to debug this if it's not a correctness issue.
